// demo/kugou/src/components/song/SongListInfo.vue
<template>
  <section class="song_list_info">
    <PubModuleHead :module-head-info="getModuleHeadInfo">
      <PubModuleDes slot="moduleDes" :description="getModuleHeadInfo.intro"/>
    </PubModuleHead>
    <AppMusicList :music-list="getMusicList"/>
  </section>
</template>

<script>
import PubModuleHead from '../public/PubModuleHead'
import PubModuleDes from '../public/PubModuleDes'
import AppMusicList from '../public/AppMusicList'
import { fetchSongListInfo } from '../../requests/songListInfo'
import loading from '../../mixins/loading'
import { mapState, mapMutations } from 'vuex'
import replaceSizeInUrl from '@/utils/replaceSizeInUrl'
export default {
  name: 'SongListInfo',
  mixins: [loading],
  components: {
    PubModuleHead,
    AppMusicList,
    PubModuleDes
  },
  computed: {
    ...mapState('song', ['songListInfo']),
    getModuleHeadInfo() {
      let data = this.songListInfo.info.list
      return {
        imgUrl: replaceSizeInUrl(data.imgurl),
        name: data.specialname,
        intro: data.intro
      }
    },
    getMusicList() {
      return this.songListInfo.songs.list.info
    }
  },
  created() {
    let songListId = this.$route.path.split('/').pop()
    this.setLoadingExcludeHeader()
    this.startLoading()
    this.getSongListInfo(songListId)
  },
  methods: {
    ...mapMutations(['replaceProperty']),
    getSongListInfo(songListId) {
      fetchSongListInfo({ songListId }).then(({ data }) => {
        let songListInfo = {
          info: data.info,
          songs: data.list
        }
        this.replaceProperty({
          paths: 'song.songListInfo',
          data: songListInfo
        })
        this.stopLoading()
      })
    }
  }
}
</script>

<style lang="less" scoped>
</style>

// demo/angular/src/app/views/song/song-list-info/song-list-info.component.ts
import { ResponseTypeFromServiceReq } from 'src/app/typings/index';
import { SongListInfoService } from 'src/app/services/song-list-info.service';
import replaceSizeInUrl from 'src/app/utils/replaceSizeInUrl';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-song-list-info',
  templateUrl: './song-list-info.component.html',
  styleUrls: ['./song-list-info.component.scss'],
})
export class SongListInfoComponent implements OnInit {
  songListInfo: ResponseTypeFromServiceReq<
    typeof SongListInfoService,
    'fetchSongListInfo'
  > = { info: { list: {}, songs: { list: { info: [] } } } };
  constructor(private songListInfoService: SongListInfoService) {}

  get getModuleHeadInfo() {
    // @ts-ignore
    const data = this.songListInfo.info.list;
    return {
      imgUrl: replaceSizeInUrl(data.imgurl),
      name: data.specialname,
      intro: data.intro,
    };
  }
  get getMusicList() {
    // @ts-ignore
    return this.songListInfo.songs.list.info;
  }
  async ngOnInit(): Promise<void> {
    const songListId = window.location.pathname.split('/').pop();
    if (songListId === undefined) {
      return;
    }
    this.songListInfo = await this.songListInfoService.fetchSongListInfo(
      songListId
    );
  }
}

<section class="song_list_info">
  <app-my-module-head [moduleHeadInfo]="getModuleHeadInfo">
    <app-my-module-description
      slot="moduleDes"
      [description]="getModuleHeadInfo.intro"
    >
    </app-my-module-description>
  </app-my-module-head>
  <app-my-music-list [musicList]="getMusicList"> </app-my-music-list>
</section>
