// demo/angular/src/app/views/rank/rank-info/rank-info.component.ts
import replaceSizeInUrl from 'src/app/utils/replaceSizeInUrl';
import { ResponseTypeFromServiceReq } from 'src/app/typings/index';
import { RankInfoService } from 'src/app/services/rank-info.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-rank-info',
  templateUrl: './rank-info.component.html',
  styleUrls: ['./rank-info.component.scss'],
})
export class RankInfoComponent implements OnInit {
  msg = '上次更新时间';
  rankInfo: ResponseTypeFromServiceReq<
    typeof RankInfoService,
    'fetchRankInfo'
  > = { info: {}, songs: { list: {}, timestamp: 0 } };
  constructor(private rankInfoService: RankInfoService) {}
  get getModuleHeadInfo() {
    return {
      // @ts-ignore
      imgUrl: replaceSizeInUrl(this.rankInfo.info.banner7url),
      // @ts-ignore

      name: this.rankInfo.info.rankname,
    };
  }
  get getMusicList() {
    // @ts-ignore
    return this.rankInfo.songs.list;
  }
  get formatDate() {
    // @ts-ignore
    const date = new Date(this.rankInfo.songs.timestamp * 1000);
    return (
      date.getFullYear() +
      '-' +
      String(date.getMonth() + 1).padStart(2, '0') +
      '-' +
      String(date.getDate()).padStart(2, '0')
    );
  }
  async ngOnInit(): Promise<void> {
    const rankId = window.location.pathname.split('/').pop();
    if (rankId === undefined) {
      return;
    }
    this.rankInfo = await this.rankInfoService.fetchRankInfo(rankId);
  }
}

<section class="rank_info">
  <app-my-module-head [moduleHeadInfo]="getModuleHeadInfo">
    <ng-template>
      <time class="rank_info__update_time" slot="moduleUpdateTime"
        >{{ msg }} {{ formatDate }}</time
      >
    </ng-template>
  </app-my-module-head>
  <app-my-music-list [musicList]="getMusicList">
    <ng-template let-music>
      <div
        slot="default"
        [class]="['rank_info__index', 'rank_info__index' + (music.index + 1)]"
      >
        {{ music.index + 1 }}
      </div>
    </ng-template>
  </app-my-music-list>
</section>

// demo/vue@3/src/views/rank/RankInfo.vue
<template>
  <section class="rank_info">
    <PubModuleHead :module-head-info="getModuleHeadInfo">
      <template v-slot:moduleUpdateTime>
        <time class="rank_info__update_time">{{ msg }} {{ formatDate }}</time>
      </template>
    </PubModuleHead>
    <AppMusicList :music-list="getMusicList">
      <template v-slot:index="props">
        <div
          :class="'rank_info__index ' + 'rank_info__index' + (props.data + 1)"
        >
          {{ props.data + 1 }}
        </div>
      </template>
    </AppMusicList>
  </section>
</template>

<script>
import { defineComponent } from 'vue'

import PubModuleHead from '@/components/PubModuleHead'
import AppMusicList from '@/components/AppMusicList'
import { fetchRankInfo } from '@/requests/rankInfo'
import { mapState, mapMutations } from 'vuex'
import loading from '../../mixins/loading'
import replaceSizeInUrl from '@/utils/replaceSizeInUrl'
export default defineComponent({
  name: 'RankInfo',
  mixins: [loading],

  components: {
    PubModuleHead,
    AppMusicList
  },

  data() {
    return {
      msg: '上次更新时间'
    }
  },

  computed: {
    ...mapState('rank', ['rankInfo']),
    getModuleHeadInfo() {
      return {
        imgUrl: replaceSizeInUrl(this.rankInfo.info.banner7url),
        name: this.rankInfo.info.rankname
      }
    },
    getMusicList() {
      return this.rankInfo.songs.list
    },
    formatDate() {
      let date = new Date(this.rankInfo.songs.timestamp * 1000)
      return (
        date.getFullYear() +
        '-' +
        String(date.getMonth() + 1).padStart(2, '0') +
        '-' +
        String(date.getDate()).padStart(2, '0')
      )
    }
  },

  created() {
    let rankId = this.$route.path.split('/').pop()
    this.setLoadingExcludeHeader()
    this.startLoading()
    this.getRankInfo(rankId)
  },

  methods: {
    ...mapMutations(['replaceProperty']),
    getRankInfo(rankId) {
      fetchRankInfo({ params: { rankid: rankId } }).then(res => {
        let rankInfo = {
          info: res.data.info,
          songs: res.data.songs
        }
        this.replaceProperty({
          paths: 'rank.rankInfo',
          data: rankInfo
        })
        this.stopLoading()
      })
    }
  }
})
</script>

<style lang="less" scoped>
@import (reference) '~@/styles/constant';
.rank_info__update_time {
  align-self: flex-end;

  width: 100%;
  height: 50px;
  padding-left: 16px;

  background: linear-gradient(
    to top,
    rgba(0, 0, 0, 0.6) 5%,
    rgba(107, 107, 107, 0.1) 90%,
    rgba(255, 255, 255, 0)
  );

  font-size: @font_size_med;
  line-height: 2.3;
}

.rank_info__index {
  width: 27px;
  height: 19px;
  margin-right: 10px;

  text-align: center;

  color: @white-to-black;
  border-radius: 9px;

  font-size: @font_size_small;
  line-height: 19px;
}

.rank_info__index1 {
  color: @white;
  background-color: @red;
}

.rank_info__index2 {
  color: @white;
  background-color: @orange;
}

.rank_info__index3 {
  color: @white;
  background-color: @yellow;
}
</style>
