// demo/kugou-react/src/components/public/AppMusicList.js
import React, { Component } from 'react'
import './AppMusicList.less'
class AppMusicList extends Component {
  render() {
    return (
      <ul className="music_list">
        {this.props.data.map(music => (
          <li className="music_list__item main_border_bottom" key={music.hash}>
            <div className="music_list__info" Onclick={() => this.props.play()}>
              {/* <slot :data="index" name="index" className="music_list__index" Onclick={()=>this.props.play()}></slot> */}
              <div className="music_list__name">{music.filename}</div>
            </div>
            <button className="music_list__download">
              <svg className="icon" aria-hidden="true">
                <use xlinkHref="#icon-download" />
              </svg>
            </button>
          </li>
        ))}
      </ul>
    )
  }
}
export default AppMusicList

// demo/kugou/src/components/AppMusicList.vue
<template>
  <ul class="music_list">
    <li class="music_list__item main_border_bottom" v-for="(item,index) in musicList" :key="index">
      <div class="music_list__info" @click="wantPlay(item)">
        <slot :data="index" name="index" class="music_list__index" @click="wantPlay(item)"></slot>
        <div class="music_list__name">{{item.filename}}</div>
      </div>
      <button class="music_list__download">
        <svg class="icon" aria-hidden="true">
          <use xlink:href="#icon-download"></use>
        </svg>
      </button>
    </li>
  </ul>
</template>

<script>
export default {
  name: 'AppMusicList',
  props: {
    musicList: {
      type: Array,
      default() {
        return []
      }
    }
  },
  methods: {
    wantPlay(music) {
      this.$store.commit('player/wantPlay', {
        music,
        musicList: this.$props.musicList
      })
    }
  }
}
</script>

<style lang="less" scoped>
@import (reference) '../styles/constant';
.music_list {
  padding-left: 19px;
}

.music_list__item {
  display: flex;
  align-items: center;

  box-sizing: border-box;
  width: 100%;
  height: auto;
  min-height: 72px;
  padding: 10px 0;
}

.music_list__info {
  display: flex;
  width: 100%;
  align-items: center;
}
.music_list__index {
  width: 48px;
  flex: 0 0 auto;
}
.music_list__name {
  width: calc(100% - 48px);
  flex: 1 0 auto;
}

.music_list__download {
  box-sizing: content-box;
  width: 23px;
  height: 100%;
  padding: 0 @padding_width;
}
</style>
