// demo/vue@3/src/views/song/SongListInfo.vue
<template>
  <section class="song_list_info" test-id="page-song-list-info">
    <PubModuleHead v-if="songListInfo.info.list" :module-head-info="getModuleHeadInfo">
      <template v-slot:moduleDes>
        <PubModuleDes :description="getModuleHeadInfo.intro" />
      </template>
    </PubModuleHead>
    <AppMusicList :music-list="getMusicList" />
  </section>
</template>

<script lang="ts" setup>
import { computed } from 'vue'
import { useStore } from 'vuex'
import { useRoute } from 'vue-router'

import PubModuleHead from '@/components/PubModuleHead.vue'
import PubModuleDes from '@/components/PubModuleDes.vue'
import AppMusicList from '@/components/AppMusicList.vue'
import { fetchSongListInfo } from '../../requests/songListInfo'
import { useLoading } from '@/composables/useLoading'
import type { RootState } from '@/store'
import { mapPlaylistInfo } from '@shared/domains/playlist/mapper'

const store = useStore<RootState>()
const route = useRoute()
const { startLoading, stopLoading, setLoadingExcludeHeader } = useLoading()

const songListInfo = computed(() => store.state.song.songListInfo)

const getModuleHeadInfo = computed(() => {
  const data = songListInfo.value.info.list!
  return {
    ...data,
    name: data.specialname,
    intro: data.intro
  }
})

const getMusicList = computed(() => {
  return songListInfo.value.songs.list.info
})

const getSongListInfo = (songListId: string) => {
  fetchSongListInfo({ songListId }).then(({ data }) => {
    store.commit('replaceProperty', {
      paths: 'song.songListInfo',
      data: mapPlaylistInfo(data)
    })
    stopLoading()
  })
}

const songListId = route.path.split('/').pop()
setLoadingExcludeHeader()
startLoading()
getSongListInfo(songListId!)
</script>

<style lang="less" scoped></style>

// demo/react-vite/src/features/song/info/SongListInfo.tsx
import type { FC } from 'react'
import { Fragment } from 'react'
import InfoHeader from '../../../shared/components/InfoHeader'
import AppMusicList from '../../../shared/components/AppMusicList'
import InfoDescription from '../../../shared/components/InfoDescription'
import type { PlaylistDetailSummary, PlaylistSong } from '@shared/domains/playlist/model'
interface SongListInfoProps {
  songsData: {
    list: PlaylistSong[];
  };
  listInfo: PlaylistDetailSummary;
}

const SongListInfo: FC<SongListInfoProps> = ({ songsData, listInfo }) => {
  const {
    songsData: { list: songs },
    listInfo: { specialname, imgUrl: imgurl, intro }
  } = { songsData, listInfo }

  const infoHeaderProps = {
    name: specialname,
    imgurl
  }

  return (
    <Fragment>
      <InfoHeader {...infoHeaderProps} />
      <InfoDescription description={intro} />
      <AppMusicList data={songs} test-id="page-song-list-info" />
    </Fragment>
  )
}

export default SongListInfo
