// demo/vue@3/src/views/player/PrevButton.vue
<template>
  <button class="player__btn_prev" @click="prev">
    <svg class="icon" aria-hidden="true">
      <use xlink:href="#icon-previous"></use>
    </svg>
  </button>
</template>

<script>
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'PrevButton',

  methods: {
    prev() {
      this.$store.commit('player/prev')
    }
  },
});
</script>

<style scoped>
</style>

// demo/react-vite/src/components/player/PrevButton.tsx
import type { FC } from 'react'

interface PrevButtonProps {
  prev(...args: unknown[]): unknown;
  className?: string;
}

const PrevButton: FC<PrevButtonProps> = ({ prev, className }) => {
  return (
    <button className={className} onClick={prev}>
      <svg className="icon" aria-hidden="true">
        <use xlinkHref="#icon-previous" />
      </svg>
    </button>
  )
}

export default PrevButton
