// demo/kugou/src/components/player/PrevButton.vue
<template>
  <button class="player__btn_prev" @touchstart="prev">
    <svg class="icon" aria-hidden="true">
      <use xlink:href="#icon-previous"></use>
    </svg>
  </button>
</template>

<script>
export default {
  name: 'PrevButton',
  methods: {
    prev() {
      this.$store.commit('prev')
    }
  }
}
</script>

<style scoped>

</style>

// demo/react-vite/src/features/player/components/PrevButton.tsx
import type { FC } from 'react'

interface PrevButtonProps {
  prev(...args: unknown[]): unknown;
  className?: string;
}

const PrevButton: FC<PrevButtonProps> = ({ prev, className }) => {
  return (
    <button className={className} onClick={prev}>
      <svg className="icon" aria-hidden="true">
        <use xlinkHref="#icon-previous" />
      </svg>
    </button>
  )
}

export default PrevButton
