// demo/kugou/src/components/singer/SingerInfo.vue
<template>
  <section class="singer_info">
    <PubModuleHead :module-head-info="getModuleHeadInfo">
      <PubModuleDes slot="moduleDes" :description="getModuleHeadInfo.intro"/>
    </PubModuleHead>
    <AppMusicList :music-list="getMusicList"/>
  </section>
</template>

<script>
import PubModuleHead from '../public/PubModuleHead'
import PubModuleDes from '../public/PubModuleDes'
import AppMusicList from '../public/AppMusicList'
import axios from 'axios'
import api from '../../assets/js/api.js'
import mixin from '../../mixins/index.js'

export default {
  name: 'SingerInfo',
  mixins: [mixin],
  components: {
    PubModuleHead,
    AppMusicList,
    PubModuleDes
  },
  data: function() {
    return {
      singerInfo: {
        info: {},
        data: []
      }
    }
  },
  computed: {
    getModuleHeadInfo() {
      return this.singerInfo.info
    },
    getMusicList() {
      return this.singerInfo.data
    }
  },
  created() {
    let singerId = this.$route.path.split('/').pop()
    this.getSingerInfo(singerId)
  },
  methods: {
    getSingerInfo(singerId) {
      axios
        .get(api.singerInfo.replace(/singerId?/i, singerId))
        .then(({ data }) => {
          let singerInfo = {
            info: {
              id: data.info.singerid,
              name: data.info.singername,
              count: data.info.songcount,
              albumcount: data.info.albumcount,
              imgUrl: this.$_xsl__replaceImgUrlSize(data.info.imgurl),
              intro: data.info.intro
            },
            data: data.songs.list
          }
          data.songs.list.forEach(obj => {
            obj.name = obj.filename
            // obj.path='/singer/info/'+obj.id
          })
          Object.assign(this.singerInfo, singerInfo)
          this.singerInfo = singerInfo
        })
        .catch(er => {
          alert(er)
        })
    }
  }
}
</script>

<style scoped lang="less">
</style>

// demo/angular/src/app/views/singer/singer-info/singer-info.component.ts
import { ResponseTypeFromServiceReq } from 'src/app/typings/index';
import { SingerInfoService } from './../../../services/singer-info.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-singer-info',
  templateUrl: './singer-info.component.html',
  styleUrls: ['./singer-info.component.scss'],
})
export class SingerInfoComponent implements OnInit {
  singerInfo: ResponseTypeFromServiceReq<
    typeof SingerInfoService,
    'fetchSingerInfo'
  > = { info: {}, data: [] };
  constructor(private singerInfoService: SingerInfoService) {}
  get getModuleHeadInfo() {
    // @ts-ignore
    return this.singerInfo.info;
  }
  get getMusicList() {
    // @ts-ignore
    return this.singerInfo.data;
  }
  async ngOnInit(): Promise<void> {
    const singerId = window.location.pathname.split('/').pop();
    if (singerId === undefined) {
      return;
    }
    this.singerInfo = await this.singerInfoService.fetchSingerInfo(singerId);
  }
}

<section class="singer_info">
  <app-my-module-head [moduleHeadInfo]="getModuleHeadInfo">
    <app-my-module-description
      slot="moduleDes"
      [description]="getModuleHeadInfo.intro"
    >
    </app-my-module-description>
  </app-my-module-head>
  <app-my-music-list [musicList]="getMusicList"> </app-my-music-list>
</section>
