// demo/react-vite/src/components/player/NextButton.tsx
import type { FC } from 'react'

interface NextButtonProps {
  next(...args: unknown[]): unknown;
  className?: string;
}

const NextButton: FC<NextButtonProps> = ({ next, className }) => {
  return (
    <button className={className} onClick={next}>
      <svg className="icon" aria-hidden="true">
        <use xlinkHref="#icon-next" />
      </svg>
    </button>
  )
}

export default NextButton

// demo/kugou/src/components/player/NextButton.vue
<template>
  <button class="next_button" @touchstart="next">
    <svg class="icon" aria-hidden="true">
      <use xlink:href="#icon-next"></use>
    </svg>
  </button>
</template>

<script>
export default {
  name: 'nextButton',
  methods: {
    next() {
      this.$store.commit('next')
    }
  }
}
</script>

<style scoped>

</style>
