// demo/kugou/src/components/player/PrevButton.vue
<template>
  <button class="player__btn_prev" @touchstart="prev">
    <svg class="icon" aria-hidden="true">
      <use xlink:href="#icon-previous"></use>
    </svg>
  </button>
</template>

<script>
export default {
  name: 'PrevButton',
  methods: {
    prev() {
      this.$store.commit('prev')
    }
  }
}
</script>

<style scoped>

</style>

// demo/react/src/components/player/PrevButton.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
class PrevButton extends Component {
  render() {
    const { prev, className } = this.props
    return (
      <button className={className} onClick={prev}>
        <svg className="icon" aria-hidden="true">
          <use xlinkHref="#icon-previous" />
        </svg>
      </button>
    )
  }
}
PrevButton.propTypes = {
  prev: PropTypes.func.isRequired,
  className: PropTypes.string
}
export default PrevButton
