// demo/react-vite/src/components/public/AppHeader.tsx
import type { FC } from 'react'
import logo__text from '../../assets/images/logo__text.png'
import { NavLink } from 'react-router-dom'
import styles from './AppHeader.module.less'
import { root, search } from '../../constants/router'

const AppHeader: FC = () => {
  const goBack = () => {
    window.history.go(-1)
  }

  return (
    <header className={styles.AppHeader}>
      <button className={styles.AppHeader__back} onClick={goBack}>
        <svg className="icon" aria-hidden="true">
          <use xlinkHref="#icon-arrow-left" />
        </svg>
      </button>
      <NavLink to={root}>
        <img className={styles.AppHeader__logo} src={logo__text} alt="logo" />
      </NavLink>
      <NavLink
        className={styles.AppHeader__searchBtn}
        to={search}
        // @click.native="bus.$emit('searchBtnClicked')"
      >
        <svg className="icon" aria-hidden="true">
          <use xlinkHref="#icon-search" />
        </svg>
      </NavLink>
    </header>
  )
}

export default AppHeader

// demo/kugou/src/components/public/AppHeader.vue
<template>
  <header class="header">
    <button class="header__back arrow arrow--left" @click="goBack"></button>
    <router-link to="/">
      <img class="header__logo" src="@/assets/images/logo.png">
    </router-link>
    <router-link
      class="header__search_btn"
      to="/search/index"
      @click.native="bus.$emit('searchBtnClicked')"
    >
      <svg class="icon" aria-hidden="true">
        <use xlink:href="#icon-search"></use>
      </svg>
    </router-link>
  </header>
</template>

<script>
import bus from '../../assets/js/bus.js'
export default {
  name: 'AppHeader',
  data() {
    return {
      bus: bus
    }
  },
  methods: {
    goBack() {
      history.go(-1)
    }
  }
}
</script>

<style lang="less" scoped>
@import (reference) '../../assets/css/constant.less';
.header {
  display: flex;
  align-items: center;
  justify-content: space-between;

  padding: 0 12px;

  color: @white;
  background: @theme-color;
}
.header__logo {
  width: 131px;
  height: 30px;
  margin: auto;
}
.header__back {
  width: 16px;
  height: 16px;

  transform: rotate(-45deg) translateY(-2px);

  border-width: 2.2px;
  border-color: @white;
}
.header__search_btn {
  display: block;

  width: 27px;
  height: 27px;

  transform: translate(1px, -3px);

  font-size: 27px;
}
</style>
