// demo/kugou/src/components/singer/SingerList.vue
<template>
  <section class="singer_list">
    <PubModuleTitle :title="singerList.info.name"/>
    <ul class="singer_list__list" ref="lazyLoadRoot">
      <li
        class="singer_list__item main_border_bottom"
        v-for="(item,index) in singerList.data"
        :key="index"
      >
        <router-link :to="item.path" class="singer_list__link">
          <img
            class="singer_list__img lazy_image"
            ref="lazyImages"
            :src="logo__grey"
            :data-src="item.imgUrl"
          >
          <div class="singer_list__name">{{item.name}}</div>
        </router-link>
      </li>
    </ul>
  </section>
</template>

<script>
import PubModuleTitle from '../public/PubModuleTitle'
import { fetchSingerList } from '../../requests/singerList'
import loading from '../../mixins/loading'
import { lazyLoad } from '@/utils'
import { mapState, mapMutations } from 'vuex'
import replaceSizeInUrl from '@/utils/replaceSizeInUrl'
export default {
  name: 'SingerList',
  mixins: [loading],
  components: {
    PubModuleTitle
  },
  computed: {
    ...mapState('images', ['logo__grey']),
    ...mapState('singer', ['singerList']),
    ...mapState('loading', {
      isLoadingShow: 'isShow'
    })
  },
  watch: {
    'singerList.data': {
      handler: function(newArray) {
        if (newArray.length === 0) {
          return
        }
        this.$nextTick(() =>
          lazyLoad(this.$refs.lazyImages, { root: this.$refs.lazyLoadRoot })
        )
      },
      immediate: true
    }
  },
  created() {
    // todo add scrollRemember
    let singerListId = this.$route.path.split('/').pop()
    if (Number(singerListId) !== this.singerList.info.id) {
      this.setLoadingExcludeHeader()
      this.startLoading()
      this.getSingerList(singerListId)
    }
  },
  methods: {
    ...mapMutations(['replaceProperty']),
    getSingerList(singerListId) {
      fetchSingerList({ params: { singerListId } }).then(({ data }) => {
        let singerList = {
          info: {
            id: data.classid,
            name: data.classname,
            count: data.singers.total
          },
          data: data.singers.list.info
        }
        data.singers.list.info.forEach(obj => {
          obj.id = obj.singerid
          obj.name = obj.singername
          obj.imgUrl = replaceSizeInUrl(obj.imgurl)
          obj.path = '/singer/info/' + obj.id
        })
        this.replaceProperty({
          paths: 'singer.singerList',
          data: singerList
        })
        this.stopLoading()
      })
    }
  }
}
</script>

<style scoped lang="less">
@import (reference) '../../assets/css/constant.less';
.singer_list {
  font-size: 19px;
}
.singer_list__list {
  overflow: scroll;

  box-sizing: border-box;
  height: calc(100% - @module_title_height);
}
.singer_list__item {
  height: 88px;
}
.singer_list__link {
  display: flex;
  align-items: center;

  height: 100%;
}
.singer_list__img {
  display: block;

  width: 61px;
  height: 61px;
  margin: 0 18px 0 @padding_width;
}
</style>

// demo/angular/src/app/views/singer/singer-list/singer-list.component.ts
import { lazyLoad } from 'src/app/utils';
import { ResponseTypeFromServiceReq } from 'src/app/typings/index';
import { SingerListService } from './../../../services/singer-list.service';
import {
  Component,
  OnInit,
  SimpleChanges,
  ViewChild,
  ViewChildren,
} from '@angular/core';

@Component({
  selector: 'app-singer-list',
  templateUrl: './singer-list.component.html',
  styleUrls: ['./singer-list.component.scss'],
})
export class SingerListComponent implements OnInit {
  // @ts-ignore
  @ViewChild('lazyLoadRoot') lazyLoadRoot: ElementRef<HTMLImageElement>;
  // @ts-ignore
  @ViewChildren('lazyImages') lazyImages: ElementRef<HTMLImageElement>;

  singerList: ResponseTypeFromServiceReq<
    typeof SingerListService,
    'fetchSingerList'
  > = {
    info: {
      id: '',
      name: '',
      count: 0,
    },
    data: [],
  };
  constructor(private singerListService: SingerListService) {}
  get singerListData() {
    // @ts-ignore
    return this.singerList.data;
  }
  get singerName() {
    // @ts-ignore
    return this.singerList.info.name;
  }
  async ngOnInit(): Promise<void> {
    const singerListId = window.location.pathname.split('/').pop();
    if (singerListId === undefined) {
      return;
    }
    this.singerList = await this.singerListService.fetchSingerList(
      singerListId
    );
    requestAnimationFrame(() => {
      //todo ? why ngOnChanges not work here?
      this.onSingerListChange();
    });
  }
  onSingerListChange() {
    // @ts-ignore
    if (this.singerList.data.length === 0 || this.lazyImages === undefined) {
      return;
    }
    lazyLoad(
      // @ts-ignore
      this.lazyImages.toArray().map((ref) => ref.nativeElement),
      {
        root: this.lazyLoadRoot.nativeElement,
      }
    );
  }
}

<section class="singer_list">
  <app-my-module-title [title]="singerName"></app-my-module-title>
  <ul class="singer_list__list" #lazyLoadRoot>
    <li
      class="singer_list__item main_border_bottom"
      *ngFor="let item of singerListData"
    >
      <a [routerLink]="item.path" class="singer_list__link">
        <img
          class="singer_list__img lazy_image"
          #lazyImages
          src="assets/images/logo__grey.png"
          [attr.data-src]="item.imgUrl"
        />
        <div class="singer_list__name">{{ item.name }}</div>
      </a>
    </li>
  </ul>
</section>
