// demo/vue@3/src/views/singer/SingerList.vue
<template>
  <section class="singer_list">
    <PubModuleTitle :title="singerList.info.name"/>
    <ul class="singer_list__list" ref="lazyLoadRoot">
      <li
        class="singer_list__item main_border_bottom"
        v-for="(item,index) in singerList.data"
        :key="index"
      >
        <router-link :to="'/singer/info/' + item.singerid" class="singer_list__link">
          <img
            class="singer_list__img lazy_image"
            :ref="el => saveImageRef(index, el as HTMLImageElement)"
            :src="logo__grey"
            :data-src="replaceSizeInUrl(item.imgurl)"
          >
          <div class="singer_list__name">{{item.singername}}</div>
        </router-link>
      </li>
    </ul>
  </section>
</template>

<script lang="ts" setup>
import { ref, computed, watch, nextTick, useTemplateRef } from 'vue'
import { useStore } from 'vuex'
import type { RootState } from '@/store'
import { useRoute } from 'vue-router'

import PubModuleTitle from '@/components/PubModuleTitle.vue'
import { fetchSingerList } from '../../requests/singerList'
import { useLoading } from '@/composables/useLoading'
import { lazyLoad } from '@/utils'
import replaceSizeInUrl from '@/utils/replaceSizeInUrl'

const store = useStore<RootState>()
const route = useRoute()
const { startLoading, stopLoading, setLoadingExcludeHeader } = useLoading()

const lazyLoadRoot = useTemplateRef<HTMLUListElement | null>('lazyLoadRoot')
const lazyImageElements = ref<(HTMLImageElement | null)[]>([])

const logo__grey = computed(() => store.state.images.logo__grey)
const singerList = computed(() => store.state.singer.singerList)

watch(()=>singerList.value.data, (newArray) => {
  if (newArray.length === 0) {
    return
  }
  lazyImageElements.value = newArray.map(() => null)
  nextTick(() =>
    lazyLoad(lazyImageElements.value as HTMLImageElement[], { root: lazyLoadRoot.value })
  )
}, {
  immediate: true
})


  // todo add scrollRemember
const singerListId = route.path.split('/').pop()
if (Number(singerListId) !== singerList.value.info.id) {
  setLoadingExcludeHeader()
  startLoading()
  getSingerList(singerListId as string)
}
const saveImageRef = (index: number, el: HTMLImageElement) => {
  lazyImageElements.value[index] = el
}

function getSingerList(singerListId: string) {
  fetchSingerList({ params: { singerListId } }).then(({ data }) => {
    const mappedList = (data.singers.list.info).map((raw) => ({
      ...raw,
      id: raw.singerid,
      name: raw.singername,
      imgUrl: replaceSizeInUrl(raw.imgurl),
      path: '/singer/info/' + raw.singerid
    }))

    const singerListData = {
      info: {
        id: data.classid,
        name: data.classname,
        count: data.singers.total
      },
      data: mappedList
    }
    store.commit('replaceProperty', {
      paths: 'singer.singerList',
      data: singerListData
    })
    stopLoading()
  })
}
</script>

<style scoped lang="less">
@import (reference) '~@/styles/constant';
.singer_list {
  font-size: 19px;
}
.singer_list__list {
  overflow: scroll;

  box-sizing: border-box;
  height: calc(100% - @module_title_height);
}
.singer_list__item {
  height: 88px;
}
.singer_list__link {
  display: flex;
  align-items: center;

  height: 100%;
}
.singer_list__img {
  display: block;

  width: 61px;
  height: 61px;
  margin: 0 18px 0 @padding_width;
}
</style>

// demo/angular/src/app/views/singer/singer-list/singer-list.component.ts
import { lazyLoad } from 'src/app/utils';
import { ResponseTypeFromServiceReq } from 'src/app/typings/index';
import { SingerListService } from './../../../services/singer-list.service';
import {
  Component,
  OnInit,
  SimpleChanges,
  ViewChild,
  ViewChildren,
} from '@angular/core';

@Component({
  selector: 'app-singer-list',
  templateUrl: './singer-list.component.html',
  styleUrls: ['./singer-list.component.scss'],
})
export class SingerListComponent implements OnInit {
  // @ts-ignore
  @ViewChild('lazyLoadRoot') lazyLoadRoot: ElementRef<HTMLImageElement>;
  // @ts-ignore
  @ViewChildren('lazyImages') lazyImages: ElementRef<HTMLImageElement>;

  singerList: ResponseTypeFromServiceReq<
    typeof SingerListService,
    'fetchSingerList'
  > = {
    info: {
      id: '',
      name: '',
      count: 0,
    },
    data: [],
  };
  constructor(private singerListService: SingerListService) {}
  get singerListData() {
    // @ts-ignore
    return this.singerList.data;
  }
  get singerName() {
    // @ts-ignore
    return this.singerList.info.name;
  }
  async ngOnInit(): Promise<void> {
    const singerListId = window.location.pathname.split('/').pop();
    if (singerListId === undefined) {
      return;
    }
    this.singerList = await this.singerListService.fetchSingerList(
      singerListId
    );
    requestAnimationFrame(() => {
      //todo ? why ngOnChanges not work here?
      this.onSingerListChange();
    });
  }
  onSingerListChange() {
    // @ts-ignore
    if (this.singerList.data.length === 0 || this.lazyImages === undefined) {
      return;
    }
    lazyLoad(
      // @ts-ignore
      this.lazyImages.toArray().map((ref) => ref.nativeElement),
      {
        root: this.lazyLoadRoot.nativeElement,
      }
    );
  }
}

<section class="singer_list">
  <app-my-module-title [title]="singerName"></app-my-module-title>
  <ul class="singer_list__list" #lazyLoadRoot>
    <li
      class="singer_list__item main_border_bottom"
      *ngFor="let item of singerListData"
    >
      <a [routerLink]="item.path" class="singer_list__link">
        <img
          class="singer_list__img lazy_image"
          #lazyImages
          src="assets/images/logo__grey.png"
          [attr.data-src]="item.imgUrl"
        />
        <div class="singer_list__name">{{ item.name }}</div>
      </a>
    </li>
  </ul>
</section>
