// demo/vue@3/src/components/AppHeader.vue
<template>
  <header class="header">
    <button class="header__back" @click="goBack">
      <svg class="icon" aria-hidden="true">
        <use xlink:href="#icon-arrow-left"></use>
      </svg>
    </button>
    <router-link to="/">
      <img class="header__logo" :src="logo__text">
    </router-link>
    <router-link
      class="header__search_btn"
      to="/search/index"
      @click.native="bus.$emit('searchBtnClicked')"
    >
      <svg class="icon" aria-hidden="true">
        <use xlink:href="#icon-search"></use>
      </svg>
    </router-link>
  </header>
</template>

<script>
import { mapState, mapMutations } from 'vuex'
import bus from '@/eventBus'
export default {
  name: 'AppHeader',
  data() {
    return {
      bus: bus
    }
  },
  computed: {
    ...mapState('images', ['logo__text']),
    ...mapState('player', ['curPlayerId'])
  },
  methods: {
    ...mapMutations('player', ['togglePlayers']),
    goBack() {
      if (this.curPlayerId === 1) {
        this.togglePlayers(1)
        return
      }
      history.go(-1)
    }
  }
}
</script>

<style lang="less" scoped>
@import (reference) '~@/styles/constant';
.header {
  display: flex;
  align-items: center;
  justify-content: space-between;

  padding: 0 12px;

  color: @white;
  background: @theme;
}
.header__logo {
  width: 131px;
  height: 30px;
  margin: auto;
}
.header__back {
  font-size: 25px;
  transform: translate(-2px, 2px);
}
.header__search_btn {
  display: block;

  width: 27px;
  height: 27px;

  transform: translate(1px, -3px);

  font-size: 27px;
}
</style>

// demo/kugou-react/src/components/public/AppHeader.js
import React, { Component } from 'react'
import logo__text from '../../assets/images/logo__text.png'
import { BrowserRouter as Router, Link } from 'react-router-dom'
import './AppHeader.less'
class AppHeader extends Component {
  constructor(props) {
    super(props)
    this.goBack = this.goBack.bind(this)
  }
  goBack() {
    // if (this.curPlayerId === 1) {
    //   this.togglePlayers(1)
    //   return
    // }
    window.history.go(-1)
  }
  render() {
    return (
      <Router>
        <header className="header">
          <button className="header__back" onClick={this.goBack}>
            <svg className="icon" aria-hidden="true">
              <use xlinkHref="#icon-arrow-left" />
            </svg>
          </button>
          <Link to="/">
            <img className="header__logo" src={logo__text} alt="logo" />
          </Link>
          <Link
            className="header__search_btn"
            to="/search/index"
            // @click.native="bus.$emit('searchBtnClicked')"
          >
            <svg className="icon" aria-hidden="true">
              <use xlinkHref="#icon-search" />
            </svg>
          </Link>
        </header>
      </Router>
    )
  }
}
export default AppHeader
