// demo/react-vite/src/components/player/PlayButton.tsx
import React, { Component } from 'react'
import classNames from 'classnames'
import './PlayButton.less'

interface PlayButtonProps {
  togglePlay(...args: unknown[]): unknown;
  isLoading: boolean;
  isPlaying: boolean;
  className?: string;
}

class PlayButton extends Component<PlayButtonProps> {
  render() {
    const { togglePlay, isLoading, isPlaying, className } = this.props
    return (
      <button className={className} onClick={togglePlay}>
        <svg
          className={classNames('icon', {
            hidden: isLoading || !isPlaying
          })}
          aria-hidden="true"
        >
          <use xlinkHref="#icon-pause" />
        </svg>
        <svg
          className={classNames('icon', 'PlayButton__loading', {
            hidden: !isLoading
          })}
          aria-hidden="true"
          onClick={e => e.stopPropagation()}
        >
          <use xlinkHref="#icon-loading-white" />
        </svg>
        <svg
          className={classNames('icon', {
            hidden: isLoading || isPlaying
          })}
          aria-hidden="true"
        >
          <use xlinkHref="#icon-play" />
        </svg>
      </button>
    )
  }
}
export default PlayButton

// demo/vue@3/src/views/player/PlayButton.vue
<template>
  <button class="play_button" @click="togglePlay">
    <svg class="icon play_button__pause" aria-hidden="true" v-show="!isLoading&&isPlaying">
      <use xlink:href="#icon-pause"></use>
    </svg>
    <svg class="icon play_button__loading" aria-hidden="true" v-show="isLoading" @click.stop>
      <use xlink:href="#icon-loading-white"></use>
    </svg>
    <svg class="icon play_button__play" aria-hidden="true" v-show="!isLoading&&!isPlaying">
      <use xlink:href="#icon-play"></use>
    </svg>
  </button>
</template>

<script>
import { defineComponent } from 'vue';

import { mapState } from 'vuex'
export default defineComponent({
  name: 'PlayButton',

  computed: {
    ...mapState('player', ['isPlaying', 'isLoading'])
  },

  methods: {
    togglePlay() {
      this.$store.commit('player/togglePlay', undefined, { root: true })
    }
  },
});
</script>

<style scoped lang="less">
.play_button__loading {
  animation: rotate 1s linear infinite reverse;
}
</style>
