// demo/kugou/src/components/singer/SingerCategory.vue
<template>
  <section class="singer_category">
    <ul
      class="singer_category__list main_border"
      v-for="(list,list_index) in singerCategories"
      :key="list_index"
    >
      <li
        class="singer_category__item main_border_bottom"
        v-for="(item,index) in list.data"
        :key="'1'+index"
      >
        <router-link :to="item.path" class="singer_category__link">
          <div class="singer_category__title">{{item.classname}}</div>
          <button class="singer_category_btn">
            <svg class="icon" aria-hidden="true">
              <use xlink:href="#icon-arrow-right"></use>
            </svg>
          </button>
        </router-link>
      </li>
    </ul>
  </section>
</template>

<script>
import axios from 'axios'
import api from '../../assets/js/api'
import { mapState, mapMutations } from 'vuex'

export default {
  name: 'SingerCategory',
  computed: {
    ...mapState('singer', ['singerCategories'])
  },
  created() {
    this.getSingerCategories()
  },
  methods: {
    ...mapMutations(['replaceProperty']),
    getSingerCategories() {
      axios.get(api.singerCategory).then(({ data }) => {
        let singerCategories = data.list.reduce((re, obj) => {
          obj.path = '/singer/list/' + obj.classid
          let findCategories = re.find(
            o => o.category === obj.classname.substring(0, 2)
          )
          if (findCategories) {
            findCategories.data.push(obj)
          } else {
            re.push({
              category: obj.classname.substring(0, 2),
              data: [obj]
            })
          }
          return re
        }, [])
        this.replaceProperty({
          paths: 'singer.singerCategories',
          data: singerCategories
        })
      })
    }
  }
}
</script>

<style lang="less" scoped>
@import (reference) '../../assets/css/constant.less';
.singer_category__list {
  width: 347px;
  margin: 18px auto;

  // border-bottom: none;

  border-radius: 6px;
  background-color: @white;
}

.singer_category__item {
  height: 50px;
}

.singer_category__item:last-child {
  /*如果用另一种思路，设置 .singer_category__list 的 border-bottom ，
  在 iPhone6/7/8 就会失败，待测试*/
  border-bottom: none;
}

.singer_category__link {
  display: block;
  display: flex;
  align-items: center;

  height: 100%;
}

.singer_category__title {
  display: block;

  padding-left: @padding_width;
}

.singer_category_btn {
  font-size: 20px;
  margin-right: 15px;
  margin-left: auto;
}
</style>

// demo/angular/src/app/views/singer/singer-category/singer-category.component.ts
import { ResponseTypeFromServiceReq } from 'src/app/typings/index';
import { SingerCategoryService } from 'src/app/services/singer-category.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-singer-category',
  templateUrl: './singer-category.component.html',
  styleUrls: ['./singer-category.component.scss'],
})
export class SingerCategoryComponent implements OnInit {
  singerCategories: ResponseTypeFromServiceReq<
    typeof SingerCategoryService,
    'fetchSingerCategory'
  > = [];

  constructor(private singerCategoryService: SingerCategoryService) {}

  async ngOnInit(): Promise<void> {
    this.singerCategories = await this.singerCategoryService.fetchSingerCategory();
  }
}

<section class="singer_category" test-id="page-singer-category">
  <ul
    class="singer_category__list main_border"
    *ngFor="let list of singerCategories"
  >
    <li
      class="singer_category__item main_border_bottom"
      *ngFor="let item of list.data"
      test-class="list"
    >
      <a
        [routerLink]="item.path"
        class="singer_category__link"
        test-class="link"
      >
        <div class="singer_category__title">{{ item.classname }}</div>
        <button class="singer_category_btn">
          <svg class="icon" aria-hidden="true">
            <use xlink:href="#icon-arrow-right"></use>
          </svg>
        </button>
      </a>
    </li>
  </ul>
</section>
