// demo/angular/src/app/views/song/song-list/song-list.component.ts
import { SongListService, SongItem } from 'src/app/services/song-list.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-song-list',
  templateUrl: './song-list.component.html',
  styleUrls: ['./song-list.component.scss'],
})
export class SongListComponent implements OnInit {
  songList: SongItem[] = [];
  constructor(private songListService: SongListService) {}

  async ngOnInit(): Promise<void> {
    if (this.songList.length === 0) {
      this.songList = await this.songListService.fetchSongList();
    }
  }
}

<section class="song_list">
  <app-my-card-list [pubList]="songList" class="song_list__cont">
    <ng-template let-item>
      <div class="song_list__info">
        <div class="song_list__title">{{ item.title }}</div>
        <div class="song_list__star">
          <svg class="icon song_list__icon" aria-hidden="true">
            <use xlink:href="#icon-music"></use>
          </svg>
          <span class="song_list__popularity">{{ item.popularity }}</span>
        </div>
      </div>
    </ng-template>
  </app-my-card-list>
</section>

// demo/kugou-react/src/components/song/SongList.js
import React, { Component } from 'react'
import './SongList.less'
import AppList from '../public/AppList'
class SongList extends Component {
  getChildren({ title, popularity }) {
    return (
      <div className="song_list__info">
        <div className="song_list__title">{title}</div>
        <div className="song_list__star">
          <svg className="icon song_list__icon" aria-hidden="true">
            <use xlinkHref="#icon-music" />
          </svg>
          <span className="song_list__popularity">{popularity}</span>
        </div>
      </div>
    )
  }
  render() {
    const { songList } = this.props
    return <AppList data={songList} render={this.getChildren} />
  }
}
export default SongList
